### PR TITLE
Affine newmark

### PR DESCRIPTION
**Pull request by oriolcg**
This pull request contains the following new features:
- `ConstantMatrixFEOperator` for affine problems with constant LHS and time dependent RHS
- Implementation of optimizations for Affine, Constant and ConstantMatrix solvers for the Newmark method.

After this PR is accepted, I would suggest to register GridapODEs@0.6.1, so other packages can use this latest version with compatibility with Gridap@0.16 (e.g. Tutorials).

### CODE REVIEW

**Comment by santiagobadia** [comment]
@oriolcg I see that the tests are still not passing

**Comment by oriolcg** [comment]
> @oriolcg I see that the tests are still not passing

@santiagobadia , I re-run the tests and this time it passed. This is very weird, I guess that the fix that @fverdugo introduced in https://github.com/gridap/Gridap.jl/commit/6e1d5c28f45006cd745d42760313c760c7ed4f23 didn't fully solve the problem.

**Comment by fverdugo** [comment]
@oriolcg today I released Gridap v01.6.2 with the bugfix in https://github.com/gridap/Gridap.jl/pull/616 and other minor things.

Make sure that you are using this version in your tests. If the problem persists, we need to further investigate.

**Comment by oriolcg** [comment]
Thanks @fverdugo. It looks that now is consistently passing the tests. @santiagobadia, I would proceed with the PR and keep an eye to this test to see if the error is reproduced in the future.

**Review by santiagobadia — APPROVED** [review]

**Pull request merged**
